### ISSUE TITLE
Using Borg with modular init file (multiple files)

### ISSUE THREAD

**Issue by notbandali** [emacscollective/borg#90]
Helllo,

Summary: It would be nice if Borg provided convenience Elisp functions and/or Makefile rules catering to those that have a multi-file setup.

I've been using a large monolithic [init.el](https://git.bandali.eu.org/.emacs.d/tree/init.el) forever, but I've recently started breaking it down into [multiple smaller files](https://git.bandali.eu.org/.emacs.d/tree/lisp). I think it would be nice if I could somehow let Borg know that besides `init.el`, additional files matching a pattern (e.g. `lisp/bandali-*.el` in my case) are to be considered as extensions of the init file, and should be byte-compiled first as dependencies for `init.el`, e.g. for the `build-init` Makefile rule.

**Comment by tarsius** [comment]
I don't think there's an one-size-fits-all solution here. The order in which the files are compiled might matter and just doing it alphabetically doesn't seem right.

I should probably do this

```diff
diff --git a/borg.el b/borg.el
index 1076750..90880ae 100644
--- a/borg.el
+++ b/borg.el
@@ -382,11 +382,12 @@ (defun borg-activate (clone)
 
 ;;; Construction
 
-(defun borg-batch-rebuild (&optional quick)
+(defun borg-batch-rebuild (&optional quick noinit)
   "Rebuild all assimilated drones.
 
 Drones are rebuilt in alphabetic order, except that Org is built
-first.  `init.el' and `USER-REAL-LOGIN-NAME.el' are also rebuilt.
+first.  `init.el' and `USER-REAL-LOGIN-NAME.el' are also rebuilt,
+unless optional NOINIT is non-nil.
 
 This function is to be used only with `--batch'.
 
@@ -413,7 +414,8 @@ (defun borg-batch-rebuild (&optional quick)
       (if (and quick (borg-get-all drone "build-step"))
           (message "Skipping...")
         (borg-build drone))))
-  (borg-batch-rebuild-init))
+  (unless noinit
+    (borg-batch-rebuild-init)))
 
 (defun borg-batch-rebuild-init ()
   "Rebuild `init.el' and `USER-REAL-LOGIN-NAME.el'.
```

and you could then add something like this to `~/.emacs.d/Makefile`:

```
my-build:
	@rm -f *.elc
	@$(EMACS) ...
	@$(EMACS) $(EMACS_ARGUMENTS) \
	--batch -L lib/borg --load borg $(SILENCIO) \
	--funcall borg-initialize \
	--eval  '(borg-batch-rebuild nil t)' 2>&1
```

See e.g. `/home/jonas/.emacs.d/lib/magit/lisp/Makefile` for how you could specify the dependencies.

**Comment by notbandali** [comment]
Thanks. So, the purpose of the additional parameter would be to allow skipping rebuilding of the init file so that it can be built manually at the right time (in the right order) by the user, correct? If so, that makes sense to me.

As for the `Makefile` excerpt, would you please expand on your example a tad bit to include dependency specification for a small hypothetical case for future reference?

**Comment by tarsius** [comment]
```make
ELS  = bar.el
ELS += foo.el
ELS += init.el

my-build-init:
	@printf "Compiling $(ELS)\n"
	@$(EMACS) $(EMACS_ARGUMENTS) \
	--batch -L lib/borg --load borg $(SILENCIO) \
	--funcall borg-initialize \
	--funcall batch-byte-compile $(ELS)

my-build: my-build-init
	@$(EMACS) $(EMACS_ARGUMENTS) \
	--batch -L lib/borg --load borg $(SILENCIO) \
	--funcall borg-initialize \
	--eval  '(borg-batch-rebuild nil t)' 2>&1
```

**Comment by notbandali** [comment]
Thanks a bunch, and sorry for my slow reply.

I gave the above a shot, and unfortunately get an error like this:
```
init.el:581:1: Error: Cannot open load file: No such file or directory, bandali-org
make: *** [Makefile:19: my-build-init] Error 1
```
where `bandali-org` is `lisp/bandali-org.el` which I've add to `ELS` at some point before adding `init.el`. And `(require 'bandali-org)` is part of my `init.el` file.

The above error is thrown despite me explicitly extending `load-path` in my `init.el` as follows:

``` elisp
(add-to-list
 'load-path
 (expand-file-name
  (convert-standard-filename "lisp") user-emacs-directory))
```

Any thoughts?

**Comment by notbandali** [comment]
Also, on a somewhat related note (related to another error I ran into which could be related to this), it would be great if Borg supported/handled presence of `early-init.el` in addition to `init.el`, for the upcoming Emacs 27 and future versions.

**Comment by tarsius** [comment]
I have pushed a different approach to the `wip` branch. All you have to do now is set the `INIT_FILES` variable in `~/.emacs.d/Makefile`.

Of course you can add `early-init.el` there are well but I don't think Borg should compile that by default. I would suggest something like this:

```emacs-lisp
;;; early-init.el --- Archaeopteryx  -*- no-byte-compile: t -*-
(setq package-enable-at-startup nil)
(setq load-prefer-newer t)
(add-to-list 'load-path "/path/to/packed")
(add-to-list 'load-path "/path/to/auto-compile")
(require 'auto-compile)
(auto-compile-on-load-mode)
(auto-compile-on-save-mode)
;;; early-init.el ends here
```

**Comment by notbandali** [comment]
Thanks, Jonas. That's easier and cleaner.

However, unfortunately my issue(s) still remain:

1. that various `lisp/*.el` files added to `INIT_FILES` with `lisp/` added to `load-path` in `early-init.el` still aren't seen during compilation by Borg (in the following error, `lisp/bandali-org.el`):
```
Cannot open load file: No such file or directory, bandali-org
make: *** [lib/borg/borg.mk:50: build-init] Error 255
```
2. a macro or function defined in `early-init.el` is not visible to e.g. `lisp/bandali-org.el`, despite `early-init.el` being listed earlier than `lisp/bandali-org.el` in `INIT_FILES`.

Perhaps both of the above issues may share the same root cause, that each file is compiled by Borg completely separately, without the others having been loaded first?

**Comment by tarsius** [comment]
1. Sounds like some of your init files load others using `require` but without adding `~/.emacs.d/lisp` to the `load-path` first. You should either add the appropriate entry to the `load-path` in the first file that is loaded or else load the files using `load` with absolute or relative paths instead of relying on the `load-path`.
2. I just pushed a commit that causes each init file to be loaded before it is compiled. Previously this was only done.

**Comment by notbandali** [comment]
1. But as I mentioned in [an earlier comment]https://github.com/emacscollective/borg/issues/90#issuecomment-621604462), I already add `lisp/` to my `load-path` in my `early-init.el`, which is the very first file I add to `INIT_FILES` in my `Makefile`.

2. Thanks, this seems to help things partially. But unfortunately I still see errors suggesting that `early-init.el` is not loaded when compiling each file. Specifically, I define a `comment` macro in `early-init.el` which I use in various `lisp/bandali-*.el` files, but it does not seem to be recognized by Emacs when Borg is compiling the `INIT_FILES`.

**Comment by tarsius** [comment]
I suggest you add some debug statements.

**Comment by notbandali** [comment]
I tried, but I'm not quite sure. I'm suspecting it all comes down to `EMACS_ARGUMENTS ?= -Q` in `borg.mk`, possibly causing `early-init.el` to not be loaded when Borg is trying to byte-compile each file. This would explain why the things I do in `early-init.el`, including extending `load-path` and defining my macro there, don't seem to be seen by Emacs's byte-compiler when I do `make build-init` in the terminal.

**Comment by tarsius** [comment]
I think you are not using the latest tip of the `wip` branch. The code that does the init file compiling in that version looks like this:

```emacs-lisp
(defun borg-batch-rebuild-init ()
  "Rebuild `init.el' and `USER-REAL-LOGIN-NAME.el'.

This function is to be used only with `--batch'."
  (unless noninteractive
    (error "borg-batch-recompile-init is to be used only with --batch"))
  (borg-silencio "\\`%s\\.\\.\\.\\(done\\)?" ; silence use-package
    (let ((default-directory borg-user-emacs-directory))
      (dolist (file (or command-line-args-left
                        (list "init.el"
                              (concat (user-real-login-name) ".el"))))
        (when (file-exists-p file)
          (message "\n--- [%s] ---\n" file)
          (load-file file)
          (byte-recompile-file (expand-file-name file) t 0))))))
```

I don't see how that could possibly fail to load each init file before compiling it.

**Comment by notbandali** [comment]
I am indeed using the latest tip of `wip`.  I now know what the issue is: in your latest commit a54d877, you completely took out `(load-file file)`, rather than bringing it out of `when`. :-)

**Comment by tarsius** [comment]
Ah didn't force-push after fixing that.

**Comment by tarsius** [comment]
So I believe this works now. Pushed to `master` as well.
